networks:
  web_network:
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  mongo:
    image: mongo:6.0
    volumes:
      - /mnt/share/mongo:/data/db
    env_file:
      - /root/env/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    env_file:
      - /root/env/.env
    volumes:
      - ./backend:/app
      - /mnt/share/files:/app/uploads
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - ENV=production
    volumes:
      - ./frontend:/web
    environment:
      - BACKEND_URL=http://backend:8000/api

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./backend/app/uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - frontend
      - backend
    networks:
      web_network:
        ipv4_address: 172.18.0.2
