services:
  mongo:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env.example
  
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env.example
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
      args:
        - ENV=development
    volumes:
      - ./frontend:/web
    environment:
      - BACKEND_URL=http://backend:8000/api

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./backend/app/uploads:/usr/share/nginx/html/uploads:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
