services:
  mongo:
    image: mongo:6.0
    volumes:
      - /mnt/share/mongo:/data/db
    env_file:
      - /root/env/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    env_file:
      - /root/env/.env
    volumes:
      - ./backend:/app
      - /mnt/share/files:/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - ENV=production
    environment:
      - BACKEND_URL=http://backend:8000/api
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./backend/app/uploads:/usr/share/nginx/html/uploads:ro
      - /etc/ssl/iiit.ac.in.pem:/etc/ssl/iiit.ac.in.pem:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
